from . import BFS_8Rooks
from . import DFS_8Rooks
from . import UCS_8Rooks
from . import DLS_8Rooks
from . import IDS_8Rooks
from . import Greedy_8Rooks
from . import AS_8Rooks
from . import HillClimbing_8Rooks
from . import SimulatedAnnealing_8Rooks
from . import Beam_8Rooks
from . import Genetic_8Rooks
from . import AndOr_8Rooks
from . import Unobservable_8Rooks
from . import PartialObservable
from . import Backtracking_8Rooks
from . import ForwardChecking_8Rooks
from . import AC3_8Rooks